config/routes.rb
Rails.application.routes.draw do
  devise_for :managers
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
    
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    resources :items, only: [:new, :index, :show, :create, :destory]
    resources :managers, only: [:new, :index, :create]
  end
  
  namespace :public do
    resources :items, only: [:new, :index, :create]
  end
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :customer
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def show
    @customer = Customer.find(params[:id])
  end
  
  def index
    @customers = Customer.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    item = Item.new(admin_item_params)
    item.save
    redirect_to admin_items_path
  end

  def destroy
  
  
  private

  def admin_item_params
    params.require(:item).permit(:name, :image, :body, :price)
  end
  
end

app/controllers/admin/managers_controller.rb
class Admin::ManagersController < ApplicationController
  def new
  end

  def index
    @items = Item.all
  
  end

  def create
  end
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  
  def after_sign_in_path_for(resource)
    
  end
  
  def after_sign_up_path_for(resource)
    
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/admin/_header.html.erb
<div class="header">
  <div><%= link_to "LOGO", %></div>
  
  
  <div><%= link_to "商品一覧",admin_items_path %></div>
  <div><%= link_to "会員一覧", admin_managers_path%></div>
  <div><%= link_to "注文履歴一覧", %></div>
  <div><%= link_to "ジャンル一覧", %></div>
  <div><%= link_to "ログアウト", %></div>
</div>

app/views/admin/items/create.html.erb
<h2>商品新規登録</h2>

app/views/admin/items/destroy.html.erb
<h1>Admin::Items#destroy</h1>
<p>Find me in app/views/admin/items/destroy.html.erb</p>

app/views/admin/items/index.html.erb
<div>
  <div>商品一覧</div> <div>+</div>
</div>


<div>
  <% @items.each do |item| %>
  <tr>
    <th>商品ID</th> <th>商品名</th> <th>税抜き価格</th> <th>ジャンル</th> <th>ステータス</th>
  </tr>
  <tr>
    <td><%= item.id %></td> <td><%= item.name %></td> <td><%= item.price %></td>
  </tr>
  <% end %>
</div>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>

<%= form_with model: @item do |f| %>
  <div>
    <span>商品画像</span>
  </div>
  
  <div>
    <span>商品名</span>
    <%= f.text_field :name %>
  </div>
  
  <div>
    <span>商品説明</span>
    <%= f.textarea :body %>
  </div>
  
  <div>
    <span>ジャンル</span>
    <%= f.select %>
  </div>
  
  <div>
    <span>税抜き価格</span>
    <%= f.number_field :price %>
  </div>
  
  <div>
    <span>販売ステータス</span>
  </div>
  
<% end %>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>


<div>
  <div></div>
  
  <div>
    <div>
      <p>商品名</p>
    </div>
    
    <div>
      <p>商品説明</p>
    </div>
    
    <div>
      <p>ジャンル</p>
    </div>
    
    <div>
      <p>税込価格</br>
        (税抜価格)
      </p>
    </div>
    
    <div>
      <p>販売ステータス</p>
    </div>
    
  </div>
</div>

app/views/admin/managers/create.html.erb
<h1>Managers#create</h1>
<p>Find me in app/views/managers/create.html.erb</p>

app/views/admin/managers/index.html.erb
<h1>注文履歴一覧</h1>
<table>
  <tr>
    <th>購入日時</th> <th>購入者</th> <th>注文個数</th> <th>注文ステータス</th>
  </tr>
  <!--繰り返し処理each-->

  <tr>
    <% @items.each do |member|%>
    <td><%= member.timestamps %></td> <td><%= member.name%></td> <td><%= member.count %></td>
    <td></td>
    <% end %>
  </tr>
</table>

app/views/admin/managers/new.html.erb
<h1>Managers#new</h1>
<p>Find me in app/views/managers/new.html.erb</p>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/managers/index.html.erb
<h1>注文履歴一覧</h1>
<table>
  <tr>
    <th>購入日時</th> <th>購入者</th> <th>注文個数</th> <th>注文ステータス</th>
  </tr>
  <!--繰り返し処理each-->

  <tr>
    <% @items.each do |member|%>
    <td><%= member.timestamps %></td> <td><%= member.name%></td> <td><%= member.count %></td>
    <td></td>
  </tr>
</table>